
#Server Config Settings
[server]
	#The maximum number of text log entries allowed before old entries are deleted.
	#Lower if you encounter packet size problems.
	#Range: > 0
	logLimit = 100
	#The maximum number of notifications each player can have before old entries are deleted.
	#Lower if you encounter packet size problems.
	#Range: > 0
	notificationLimit = 500
	#Determines whether or not coins should be craftable via the Coin Minting Machine.
	canMintCoins = false
	#Determines whether or not coins can be melted back into their source material in the Coin Minting Machine.
	canMeltCoins = false

	#Specific Coin Minting Settings.
	[server.coin_minting]
		#Whether copper coins can be minted.
		canMintCopper = false
		#Whether iron coins can be minted.
		canMintIron = false
		#Whether gold coins can be minted.
		canMintGold = false
		#Whether emerald coins can be minted.
		canMintEmerald = false
		#Whether diamond coins can be minted.
		canMintDiamond = false
		#Whether netherite coins can be minted.
		canMintNetherite = false

	#Specific Coin Melting Settings.
	[server.coin_melting]
		#Whether copper coins can be melted.
		canMeltCopper = true
		#Whether iron coins can be melted.
		canMeltIron = true
		#Whether gold coins can be melted.
		canMeltGold = true
		#Whether emerald coins can be melted.
		canMeltEmerald = true
		#Whether diamond coins can be melted.
		canMeltDiamond = true
		#Whether netherite coins can be melted.
		canMeltNetherite = true

	#Wallet Settings.
	[server.wallet]
		#The lowest level wallet capable of converting coins in the UI.
		#0-Copper Wallet; 1-Iron Wallet; 2-Gold Wallet; 3-Emerald Wallet; 4-Diamond Wallet; 5-Netherite Wallet
		#Must be less than or equal to 'pickupLevel'.
		#Range: 0 ~ 5
		convertLevel = 1
		#The lowest level wallet capable of automatically collecting coins while equipped.
		#0-Copper Wallet; 1-Iron Wallet; 2-Gold Wallet; 3-Emerald Wallet; 4-Diamond Wallet; 5-Netherite Wallet
		#Range: 0 ~ 5
		pickupLevel = 2
		#The lowest level wallet capable of allowing transfers to/from your bank account.
		#0-Copper Wallet; 1-Iron Wallet; 2-Gold Wallet; 3-Emerald Wallet; 4-Diamond Wallet; 5-Netherite Wallet
		#Range: 0 ~ 5
		bankLevel = 5

	#Coin value display settings.
	[server.coin_value_display]
		#Tooltip type displayed on coin items.
		#DEFAULT: Conversion tooltips, explaining it's value based on the coins it can be converted to/from.
		#VALUE: Coins numerical display value as defined by the coinValueType option below. Not recommend if using the DEFAULT coinValueType.
		#Allowed Values: DEFAULT, VALUE, NONE
		coinTooltipType = "DEFAULT"
		#Value display method used throughout the mod.
		#DEFAULT: Coin Count & Icon aglomerate (1n5g for 1 netherite and 5 gold)
		#VALUE: Coin numerical display value as defined by the baseValueCoin and valueFormat config options below.
		#Allowed Values: DEFAULT, VALUE
		coinValueType = "DEFAULT"
		#Input method used for the Coin Value Input.
		#DEFAULT: Default coin input with up/down buttons for each coin type.
		#VALUE: Text box input for the coins display value.
		#Allowed Values: DEFAULT, VALUE
		coinValueInputType = "DEFAULT"
		#Coin item defined as 1 value unit for display purposes. Any coins worth less than the base coin will have a decimal value.
		baseValueCoin = "lightmanscurrency:coin_copper"
		#Value display format. Used to add currency signs to coin value displays.
		#{value} will be replaced with the coins numerical value. Only 1 should be present at any given time.
		valueFormat = "${value}"

	#Item Capacity Upgrade Settings
	[server.upgrades]
		#The amount of item storage added by the first Item Capacity upgrade (Iron).
		#Range: 1 ~ 1728
		upgradeCapacity1 = 192
		#The amount of item storage added by the second Item Capacity upgrade (Gold).
		#Range: 1 ~ 1728
		upgradeCapacity2 = 384
		#The amount of item storage added by the third Item Capacity upgrade (Diamond).
		#Range: 1 ~ 1728
		upgradeCapacity3 = 576

	#Enchantment Settings
	[server.enchantments]
		#The coin cost required to repair a single item durability point with the Money Mending enchantment.
		moneyMendingCoinCost = "lightmanscurrency:coin_copper"
		#The base radius around the player that the Coin Magnet enchantment will collect coins from.
		#Range: 0 ~ 50
		coinMagnetRangeBase = 5
		#The increase in collection radius added by each additional level of the enchantment.
		#Range: 0 ~ 50
		coinMagnetRangeLevel = 2

	#Auction House Settings
	[server.auction_house]
		#Whether the Auction House will appear on the trader list.
		#If disabled after players have interacted with it, items & money in the auction house cannot be accessed until re-enabled.
		enabled = true
		#The maximum number of days an auction can be carried out.
		#Range: > 1
		maxDuration = 30

	#Discord bot settings. Requires lightmansdiscord v0.0.3.0+ to use.
	[server.discord]
		#The channel where users can run the currency commands and where currency related announcements will be made.
		channel = "000000000000000000"
		#Prefix for currency commands.
		prefix = "!"

